# Generated by Django 5.0.1 on 2025-12-04 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0003_alter_asistencia_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('QUINCENAL', 'Quincenal'), ('SEMANAL', 'Semanal')], db_column='tipo_periodo', max_length=20)),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateField(db_column='fecha_fin')),
                ('fecha_pago', models.DateField(db_column='fecha_pago')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CALCULADA', 'Calculada'), ('CERRADA', 'Cerrada'), ('PAGADA', 'Pagada')], db_column='estado', default='ABIERTA', max_length=20)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'nominas',
                'ordering': ['-fecha_inicio', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.IntegerField(db_column='dias_trabajados', default=0)),
                ('dias_descanso', models.IntegerField(db_column='dias_descanso', default=0)),
                ('dias_vacaciones', models.IntegerField(db_column='dias_vacaciones', default=0)),
                ('dias_permiso_con_goce', models.IntegerField(db_column='dias_permiso_con_goce', default=0)),
                ('dias_permiso_sin_goce', models.IntegerField(db_column='dias_permiso_sin_goce', default=0)),
                ('dias_licencia_medica', models.IntegerField(db_column='dias_licencia_medica', default=0)),
                ('dias_ausente', models.IntegerField(db_column='dias_ausente', default=0)),
                ('salario_base_mensual', models.DecimalField(db_column='salario_base_mensual', decimal_places=2, max_digits=12)),
                ('salario_base_periodo', models.DecimalField(db_column='salario_base_periodo', decimal_places=2, max_digits=12)),
                ('salario_base_devengado', models.DecimalField(db_column='salario_base_devengado', decimal_places=2, default=0, max_digits=12)),
                ('horas_extra', models.DecimalField(db_column='horas_extra', decimal_places=2, default=0, max_digits=8)),
                ('monto_horas_extra', models.DecimalField(db_column='monto_horas_extra', decimal_places=2, default=0, max_digits=12)),
                ('bonificaciones', models.DecimalField(db_column='bonificaciones', decimal_places=2, default=0, max_digits=12)),
                ('igss', models.DecimalField(db_column='igss', decimal_places=2, default=0, max_digits=12)),
                ('isr', models.DecimalField(db_column='isr', decimal_places=2, default=0, max_digits=12)),
                ('otros_descuentos', models.DecimalField(db_column='otros_descuentos', decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(db_column='total_devengado', decimal_places=2, max_digits=12)),
                ('total_descuentos', models.DecimalField(db_column='total_descuentos', decimal_places=2, max_digits=12)),
                ('salario_neto', models.DecimalField(db_column='salario_neto', decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('CALCULADO', 'Calculado'), ('AJUSTADO', 'Ajustado'), ('PAGADO', 'Pagado')], db_column='estado', default='CALCULADO', max_length=20)),
                ('pagado', models.BooleanField(db_column='pagado', default=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia')], db_column='metodo_pago', max_length=20, null=True)),
                ('fecha_pagado', models.DateTimeField(blank=True, db_column='fecha_pagado', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('empleado', models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.RESTRICT, related_name='nominas_detalle', to='planillas.empleado')),
                ('nomina', models.ForeignKey(db_column='nomina_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='planillas.nomina')),
            ],
            options={
                'verbose_name': 'Detalle de Nómina',
                'verbose_name_plural': 'Detalles de Nómina',
                'db_table': 'nomina_detalle',
                'ordering': ['nomina', 'empleado__codigo_empleado'],
            },
        ),
        migrations.CreateModel(
            name='PagoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia')], db_column='forma_pago', max_length=20)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(db_column='moneda', default='GTQ', max_length=3)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, db_column='fecha_pago')),
                ('banco', models.CharField(blank=True, db_column='banco', max_length=100, null=True)),
                ('numero_cheque', models.CharField(blank=True, db_column='numero_cheque', max_length=50, null=True)),
                ('cuenta_bancaria', models.CharField(blank=True, db_column='cuenta_bancaria', max_length=50, null=True)),
                ('fecha_cobro', models.DateField(blank=True, db_column='fecha_cobro', null=True)),
                ('anulado', models.BooleanField(db_column='anulado', default=False)),
                ('motivo_anulacion', models.TextField(blank=True, db_column='motivo_anulacion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('nomina_detalle', models.ForeignKey(db_column='nomina_detalle_id', on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='planillas.nominadetalle')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_nomina_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Nómina',
                'verbose_name_plural': 'Pagos de Nómina',
                'db_table': 'pagos_nomina',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='idx_nominas_periodo'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['estado'], name='idx_nominas_estado'),
        ),
        migrations.AddIndex(
            model_name='nominadetalle',
            index=models.Index(fields=['nomina'], name='idx_nomina_detalle_nomina'),
        ),
        migrations.AddIndex(
            model_name='nominadetalle',
            index=models.Index(fields=['empleado'], name='idx_nomina_detalle_empleado'),
        ),
        migrations.AddIndex(
            model_name='nominadetalle',
            index=models.Index(fields=['pagado'], name='idx_nomina_detalle_pagado'),
        ),
        migrations.AddIndex(
            model_name='pagonomina',
            index=models.Index(fields=['nomina_detalle'], name='idx_pagos_nomina_detalle'),
        ),
        migrations.AddIndex(
            model_name='pagonomina',
            index=models.Index(fields=['forma_pago'], name='idx_pagos_nomina_forma'),
        ),
    ]
