# Generated by Django 5.0.1 on 2025-12-04 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0004_nominas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['activo'], name='idx_nominas_activo'),
        ),
    ]
