# Generated by Django 5.0.1 on 2025-12-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0005_add_activo_to_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominadetalle',
            name='estado',
            field=models.CharField(choices=[('CALCULADO', 'Calculado'), ('AJUSTADO', 'Ajustado'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], db_column='estado', default='CALCULADO', max_length=20),
        ),
    ]
