# Generated by Django 5.0.1 on 2025-12-19 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0006_alter_nominadetalle_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', max_length=30, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Cargo por empleado',
                'verbose_name_plural': 'Cargos por empleado',
                'db_table': 'empleado_cargos',
            },
        ),
        migrations.RemoveIndex(
            model_name='empleado',
            name='idx_empleados_puesto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['activo'], name='idx_asistencias_activo'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha'], name='idx_asistencias_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha', 'estado'], name='idx_asistencias_fecha_estado'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['activo', 'estado', 'fecha_inicio'], name='idx_nominas_activo_estado_ini'),
        ),
        migrations.AddIndex(
            model_name='nominadetalle',
            index=models.Index(fields=['activo'], name='idx_nomina_detalle_activo'),
        ),
        migrations.AddIndex(
            model_name='nominadetalle',
            index=models.Index(fields=['nomina', 'pagado'], name='idx_nom_det_nomina_pagado'),
        ),
        migrations.AddIndex(
            model_name='nominadetalle',
            index=models.Index(fields=['nomina', 'estado'], name='idx_nom_det_nomina_estado'),
        ),
        migrations.AddIndex(
            model_name='pagonomina',
            index=models.Index(fields=['anulado'], name='idx_pagos_nomina_anulado'),
        ),
        migrations.AddIndex(
            model_name='pagonomina',
            index=models.Index(fields=['fecha_pago'], name='idx_pagos_nomina_fecha'),
        ),
        migrations.AddIndex(
            model_name='pagonomina',
            index=models.Index(fields=['anulado', 'fecha_pago'], name='idx_pagos_anulado_fecha'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['codigo'], name='idx_cargos_codigo'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['nombre'], name='idx_cargos_nombre'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['activo'], name='idx_cargos_activo'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['activo', 'nombre'], name='idx_cargos_activo_nombre'),
        ),
        migrations.AddField(
            model_name='empleadocargo',
            name='cargo',
            field=models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='cargo_empleados', to='planillas.cargo'),
        ),
        migrations.AddField(
            model_name='empleadocargo',
            name='empleado',
            field=models.ForeignKey(db_column='empleado_id', on_delete=django.db.models.deletion.CASCADE, related_name='empleado_cargos', to='planillas.empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargos',
            field=models.ManyToManyField(blank=True, related_name='empleados', through='planillas.EmpleadoCargo', to='planillas.cargo'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['area_trabajo'], name='idx_empleados_area'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['activo', 'codigo_empleado'], name='idx_empleados_activo_codigo'),
        ),
        migrations.AddIndex(
            model_name='empleadocargo',
            index=models.Index(fields=['empleado'], name='idx_emp_cargo_empleado'),
        ),
        migrations.AddIndex(
            model_name='empleadocargo',
            index=models.Index(fields=['cargo'], name='idx_emp_cargo_cargo'),
        ),
        migrations.AddIndex(
            model_name='empleadocargo',
            index=models.Index(fields=['cargo', 'empleado'], name='idx_emp_cargo_cargo_empleado'),
        ),
        migrations.AddConstraint(
            model_name='empleadocargo',
            constraint=models.UniqueConstraint(fields=('empleado', 'cargo'), name='uq_empleado_cargo'),
        ),
    ]
