# Generated by Django 5.0.1 on 2025-11-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoBloquera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_bloque', models.CharField(max_length=100)),
                ('dimensiones', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_produccion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Producto Bloquera',
                'verbose_name_plural': 'Productos Bloquera',
                'db_table': 'productos_bloquera',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='productos_b_codigo_a99db4_idx'), models.Index(fields=['nombre'], name='productos_b_nombre_5f183a_idx'), models.Index(fields=['tipo_bloque'], name='productos_b_tipo_bl_71fbea_idx'), models.Index(fields=['activo'], name='productos_b_activo_da1ba1_idx')],
            },
        ),
    ]
