# Generated by Django 5.0.1 on 2025-11-24 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloquera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventarioBloquera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('TRANSFERENCIA', 'Transferencia'), ('DEVOLUCION', 'Devolución')], db_column='tipo', max_length=20)),
                ('cantidad', models.IntegerField(db_column='cantidad', help_text='Cantidad del movimiento (positiva para entrada/salida, puede ser negativa para ajustes)')),
                ('stock_anterior', models.IntegerField(db_column='stock_anterior', default=0, help_text='Stock antes del movimiento')),
                ('stock_nuevo', models.IntegerField(db_column='stock_nuevo', default=0, help_text='Stock después del movimiento')),
                ('motivo', models.CharField(blank=True, db_column='motivo', help_text='Motivo del movimiento', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_column='fecha_movimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bloquera.productobloquera')),
                ('usuario', models.ForeignKey(db_column='usuario_id', help_text='Usuario que realizó el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario_bloquera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario Bloquera',
                'verbose_name_plural': 'Movimientos de Inventario Bloquera',
                'db_table': 'movimientos_inventario_bloquera',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['producto', 'fecha_movimiento'], name='movimientos_product_3d0e42_idx'), models.Index(fields=['tipo', 'fecha_movimiento'], name='movimientos_tipo_bc2092_idx'), models.Index(fields=['fecha_movimiento'], name='movimientos_fecha_m_066545_idx')],
            },
        ),
    ]
