# Generated by Django 5.0.1 on 2025-12-13 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloquera', '0003_add_precio_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccionBloquera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', help_text='Código único de la orden (ej: OP-2025-0001)', max_length=20, unique=True)),
                ('cantidad_solicitada', models.IntegerField(db_column='cantidad_solicitada', help_text='Cantidad total solicitada para la orden', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio', help_text='Fecha de inicio de la orden de producción')),
                ('fecha_fin_estimada', models.DateField(blank=True, db_column='fecha_fin_estimada', help_text='Fecha estimada de finalización', null=True)),
                ('supervisor', models.CharField(blank=True, db_column='supervisor', help_text='Responsable/supervisor de la orden', max_length=120, null=True)),
                ('notas', models.TextField(blank=True, db_column='notas', help_text='Notas adicionales sobre la orden', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_column='estado', default='PENDIENTE', help_text='Estado actual de la orden de producción', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('producto', models.ForeignKey(db_column='producto_id', help_text='Producto a producir', on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes_produccion', to='bloquera.productobloquera')),
            ],
            options={
                'verbose_name': 'Orden de Producción Bloquera',
                'verbose_name_plural': 'Órdenes de Producción Bloquera',
                'db_table': 'ordenes_produccion_bloquera',
                'ordering': ['-fecha_inicio', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoteProduccionBloquera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lote', models.DateField(db_column='fecha_lote', help_text='Fecha en que se produjo este lote')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio', help_text='Hora de inicio de la producción del lote')),
                ('hora_fin', models.TimeField(db_column='hora_fin', help_text='Hora de finalización de la producción del lote')),
                ('cantidad_producida', models.IntegerField(db_column='cantidad_producida', help_text='Cantidad total producida en este lote', validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_defectuosa', models.IntegerField(db_column='cantidad_defectuosa', default=0, help_text='Cantidad de productos defectuosos en este lote', validators=[django.core.validators.MinValueValidator(0)])),
                ('calidad', models.CharField(choices=[('MALA', 'Mala'), ('REGULAR', 'Regular'), ('BUENA', 'Buena'), ('EXCELENTE', 'Excelente')], db_column='calidad', help_text='Calidad del lote producido', max_length=20)),
                ('supervisor', models.CharField(db_column='supervisor', help_text='Supervisor que registró este lote (snapshot de la orden)', max_length=120)),
                ('notas', models.TextField(blank=True, db_column='notas', help_text='Notas adicionales sobre este lote', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('orden', models.ForeignKey(db_column='orden_id', help_text='Orden de producción a la que pertenece este lote', on_delete=django.db.models.deletion.CASCADE, related_name='lotes_produccion', to='bloquera.ordenproduccionbloquera')),
            ],
            options={
                'verbose_name': 'Lote de Producción Bloquera',
                'verbose_name_plural': 'Lotes de Producción Bloquera',
                'db_table': 'lotes_produccion_bloquera',
                'ordering': ['-fecha_lote', '-hora_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='ordenproduccionbloquera',
            index=models.Index(fields=['codigo'], name='idx_op_codigo'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccionbloquera',
            index=models.Index(fields=['estado'], name='idx_op_estado'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccionbloquera',
            index=models.Index(fields=['producto'], name='idx_op_producto'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccionbloquera',
            index=models.Index(fields=['fecha_inicio'], name='idx_op_fecha_inicio'),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccionbloquera',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_solicitada__gte', 0)), name='chk_op_cant_solicitada'),
        ),
        migrations.AddConstraint(
            model_name='ordenproduccionbloquera',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin_estimada__isnull', True), ('fecha_fin_estimada__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_op_fechas'),
        ),
        migrations.AddIndex(
            model_name='loteproduccionbloquera',
            index=models.Index(fields=['orden'], name='idx_lotes_orden'),
        ),
        migrations.AddIndex(
            model_name='loteproduccionbloquera',
            index=models.Index(fields=['fecha_lote'], name='idx_lotes_fecha'),
        ),
        migrations.AddIndex(
            model_name='loteproduccionbloquera',
            index=models.Index(fields=['calidad'], name='idx_lotes_calidad'),
        ),
        migrations.AddConstraint(
            model_name='loteproduccionbloquera',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='chk_lote_horas'),
        ),
        migrations.AddConstraint(
            model_name='loteproduccionbloquera',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cantidad_producida__gte', 0), ('cantidad_defectuosa__gte', 0), ('cantidad_defectuosa__lte', models.F('cantidad_producida')))), name='chk_lote_cantidades'),
        ),
    ]
