# Generated by Django 5.0.1 on 2025-11-25 01:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ferreteria', '0005_movimientoinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(db_column='numero_factura', help_text='Número único de factura', max_length=20, unique=True, verbose_name='Número de Factura')),
                ('empresa', models.CharField(choices=[('FERRETERIA', 'Ferretería'), ('BLOQUERA', 'Bloquera'), ('PIEDRINERA', 'Piedrinera')], db_column='empresa', max_length=20, verbose_name='Empresa')),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('descuento', models.DecimalField(db_column='descuento', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('total', models.DecimalField(db_column='total', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('total_pagado', models.DecimalField(db_column='total_pagado', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Pagado')),
                ('saldo_pendiente', models.DecimalField(db_column='saldo_pendiente', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo Pendiente')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Pago'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], db_column='estado', default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True, verbose_name='Observaciones')),
                ('fecha_factura', models.DateTimeField(db_column='fecha_factura', default=django.utils.timezone.now, verbose_name='Fecha de Factura')),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='fecha_vencimiento', help_text='Fecha de vencimiento para pagos a crédito', null=True, verbose_name='Fecha de Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ferreteria.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó la factura')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
                'ordering': ['-fecha_factura', '-numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('producto_codigo', models.CharField(db_column='producto_codigo', max_length=50, verbose_name='Código del Producto')),
                ('producto_nombre', models.CharField(db_column='producto_nombre', max_length=200, verbose_name='Nombre del Producto')),
                ('producto_empresa', models.CharField(choices=[('FERRETERIA', 'Ferretería'), ('BLOQUERA', 'Bloquera'), ('PIEDRINERA', 'Piedrinera')], db_column='producto_empresa', max_length=20, verbose_name='Empresa del Producto')),
                ('cantidad', models.DecimalField(db_column='cantidad', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='precio_unitario', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(db_column='descuento', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['producto', 'productobloquera', 'agregadopiedrinera']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('factura', models.ForeignKey(db_column='factura_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'detalles_factura',
                'ordering': ['factura', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('FIADO', 'Fiado')], db_column='tipo_pago', max_length=20, verbose_name='Tipo de Pago')),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('referencia', models.CharField(blank=True, db_column='referencia', help_text='Número de tarjeta, referencia de transferencia, etc.', max_length=100, null=True, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True, verbose_name='Observaciones')),
                ('fecha_pago', models.DateTimeField(db_column='fecha_pago', default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('factura', models.ForeignKey(db_column='factura_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura', verbose_name='Factura')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró el pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='facturas_numero__52cd80_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente', 'fecha_factura'], name='facturas_cliente_57ecf5_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado', 'fecha_factura'], name='facturas_estado_9f9485_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['empresa', 'fecha_factura'], name='facturas_empresa_6f82cf_idx'),
        ),
        migrations.AddIndex(
            model_name='detallefactura',
            index=models.Index(fields=['factura', 'producto_empresa'], name='detalles_fa_factura_112a19_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['factura', 'fecha_pago'], name='pagos_factura_3c0263_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['tipo_pago', 'fecha_pago'], name='pagos_tipo_pa_763a07_idx'),
        ),
    ]
