# Generated by Django 5.0.1 on 2025-11-25 01:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('facturacion', '0001_initial'),
        ('ferreteria', '0005_movimientoinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='producto_empresa',
            field=models.CharField(choices=[('FERRETERIA', 'Ferretería'), ('BLOQUERA', 'Bloquera'), ('PIEDRINERA', 'Piedrinera'), ('MIXTA', 'Mixta (Múltiples Empresas)')], db_column='producto_empresa', max_length=20, verbose_name='Empresa del Producto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='empresa',
            field=models.CharField(choices=[('FERRETERIA', 'Ferretería'), ('BLOQUERA', 'Bloquera'), ('PIEDRINERA', 'Piedrinera'), ('MIXTA', 'Mixta (Múltiples Empresas)')], db_column='empresa', help_text='Empresa principal de la factura. Si incluye productos de múltiples empresas, seleccione "Mixta"', max_length=20, verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(db_column='numero_cotizacion', help_text='Número único de cotización', max_length=20, unique=True, verbose_name='Número de Cotización')),
                ('empresa', models.CharField(choices=[('FERRETERIA', 'Ferretería'), ('BLOQUERA', 'Bloquera'), ('PIEDRINERA', 'Piedrinera'), ('MIXTA', 'Mixta (Múltiples Empresas)')], db_column='empresa', max_length=20, verbose_name='Empresa')),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('descuento', models.DecimalField(db_column='descuento', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('total', models.DecimalField(db_column='total', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al Cliente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida')], db_column='estado', default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True, verbose_name='Observaciones')),
                ('condiciones', models.TextField(blank=True, db_column='condiciones', help_text='Términos y condiciones de la cotización', null=True, verbose_name='Condiciones de la Cotización')),
                ('fecha_vencimiento', models.DateField(db_column='fecha_vencimiento', help_text='Fecha hasta la cual la cotización es válida', verbose_name='Fecha de Vencimiento')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, db_column='fecha_aceptacion', help_text='Fecha en que el cliente aceptó la cotización', null=True, verbose_name='Fecha de Aceptación')),
                ('fecha_cotizacion', models.DateTimeField(db_column='fecha_cotizacion', default=django.utils.timezone.now, verbose_name='Fecha de Cotización')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ferreteria.cliente', verbose_name='Cliente')),
                ('factura_generada', models.OneToOneField(blank=True, db_column='factura_id', help_text='Factura generada a partir de esta cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='facturacion.factura', verbose_name='Factura Generada')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó la cotización')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_cotizacion', '-numero_cotizacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('producto_codigo', models.CharField(db_column='producto_codigo', max_length=50, verbose_name='Código del Producto')),
                ('producto_nombre', models.CharField(db_column='producto_nombre', max_length=200, verbose_name='Nombre del Producto')),
                ('producto_empresa', models.CharField(choices=[('FERRETERIA', 'Ferretería'), ('BLOQUERA', 'Bloquera'), ('PIEDRINERA', 'Piedrinera'), ('MIXTA', 'Mixta (Múltiples Empresas)')], db_column='producto_empresa', max_length=20, verbose_name='Empresa del Producto')),
                ('cantidad', models.DecimalField(db_column='cantidad', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='precio_unitario', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(db_column='descuento', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['producto', 'productobloquera', 'agregadopiedrinera']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('cotizacion', models.ForeignKey(db_column='cotizacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'db_table': 'detalles_cotizacion',
                'ordering': ['cotizacion', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero_cotizacion'], name='cotizacione_numero__e967de_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente', 'fecha_cotizacion'], name='cotizacione_cliente_91ddf3_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado', 'fecha_cotizacion'], name='cotizacione_estado_ff1d73_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['empresa', 'fecha_cotizacion'], name='cotizacione_empresa_558fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['fecha_vencimiento'], name='cotizacione_fecha_v_c4efc8_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecotizacion',
            index=models.Index(fields=['cotizacion', 'producto_empresa'], name='detalles_co_cotizac_88fb05_idx'),
        ),
    ]
