# Generated by Django 5.0.1 on 2025-11-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_detallefactura_producto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Pago'), ('PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada'), ('MORA', 'En Mora')], db_column='estado', default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
    ]
