# Generated by Django 5.0.1 on 2025-11-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0003_alter_usuario_managers_alter_usuario_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('operador', 'Operador')], default='vendedor', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('grupos', models.ManyToManyField(blank=True, help_text='Grupos de Django asociados a este rol', related_name='roles_personalizados', to='auth.group', verbose_name='Grupos de Django')),
                ('permisos', models.ManyToManyField(blank=True, help_text='Permisos asociados a este rol', related_name='roles', to='auth.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_personalizado',
            field=models.ForeignKey(blank=True, help_text='Rol personalizado del sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='authentication.rol', verbose_name='Rol Personalizado'),
        ),
    ]
