# Generated by Django 5.0.1 on 2025-11-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0004_alter_usuario_rol_rol_usuario_rol_personalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol_personalizado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('operador', 'Operador')], default='vendedor', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('vendedor', 'Vendedor'), ('operador', 'Operador')], help_text='Rol básico del sistema', max_length=20, unique=True, verbose_name='Rol')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de las funciones y responsabilidades de este rol', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este rol está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('grupos', models.ManyToManyField(blank=True, help_text='Grupos de Django asociados a este rol', related_name='configuraciones_rol', to='auth.group', verbose_name='Grupos de Django')),
                ('permisos', models.ManyToManyField(blank=True, help_text='Permisos asociados a este rol', related_name='configuraciones_rol', to='auth.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Configuración de Rol',
                'verbose_name_plural': 'Configuraciones de Roles',
                'db_table': 'configuraciones_rol',
                'ordering': ['rol'],
            },
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
