# Generated by Django 5.0.1 on 2025-11-23 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(db_column='placa', max_length=15, unique=True)),
                ('marca', models.CharField(db_column='marca', max_length=100)),
                ('modelo', models.CharField(db_column='modelo', max_length=100)),
                ('capacidad_m3', models.DecimalField(db_column='capacidad_m3', decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado_actual', models.CharField(db_column='estado_actual', max_length=20)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, db_column='fecha_ultimo_mantenimiento', null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, db_column='fecha_proximo_mantenimiento', null=True)),
                ('kilometraje', models.IntegerField(db_column='kilometraje', default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_operacion', models.IntegerField(db_column='horas_operacion', default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumo_l_100km', models.DecimalField(db_column='consumo_l_100km', decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('seguro_vigente', models.BooleanField(db_column='seguro_vigente', default=True)),
                ('revision_tecnica_vigente', models.BooleanField(db_column='revision_tecnica_vigente', default=True)),
                ('documentacion_vigente', models.BooleanField(db_column='documentacion_vigente', default=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'db_table': 'camiones',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='AgregadoPiedrinera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', max_length=20, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('tipo', models.CharField(db_column='tipo', max_length=50)),
                ('granulometria', models.CharField(blank=True, db_column='granulometria', max_length=50, null=True)),
                ('precio_venta_m3', models.DecimalField(db_column='precio_venta_m3', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_produccion_m3', models.DecimalField(db_column='costo_produccion_m3', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_actual_m3', models.DecimalField(db_column='stock_actual_m3', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo_m3', models.DecimalField(db_column='stock_minimo_m3', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ubicacion', models.CharField(blank=True, db_column='ubicacion', max_length=100, null=True)),
                ('humedad_porcentaje', models.DecimalField(blank=True, db_column='humedad_porcentaje', decimal_places=2, max_digits=5, null=True)),
                ('calidad', models.CharField(blank=True, db_column='calidad', max_length=30, null=True)),
                ('proveedor', models.CharField(blank=True, db_column='proveedor', max_length=150, null=True)),
                ('fecha_ultima_entrada', models.DateField(blank=True, db_column='fecha_ultima_entrada', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Agregado Piedrinera',
                'verbose_name_plural': 'Agregados Piedrinera',
                'db_table': 'agregados_piedrinera',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['nombre'], name='idx_agregados_nombre'), models.Index(fields=['tipo'], name='idx_agregados_tipo'), models.Index(fields=['proveedor'], name='idx_agregados_proveedor')],
            },
        ),
        migrations.AddConstraint(
            model_name='agregadopiedrinera',
            constraint=models.CheckConstraint(check=models.Q(('stock_actual_m3__gte', 0)), name='chk_agregados_stock_actual_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='agregadopiedrinera',
            constraint=models.CheckConstraint(check=models.Q(('stock_minimo_m3__gte', 0)), name='chk_agregados_stock_minimo_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='agregadopiedrinera',
            constraint=models.CheckConstraint(check=models.Q(('costo_produccion_m3__gte', 0), ('precio_venta_m3__gte', 0)), name='chk_agregados_precio_nonneg'),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['placa'], name='idx_camiones_placa'),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['marca', 'modelo'], name='idx_camiones_marca_modelo'),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['estado_actual'], name='idx_camiones_estado'),
        ),
        migrations.AddIndex(
            model_name='camion',
            index=models.Index(fields=['fecha_proximo_mantenimiento'], name='idx_camiones_prox_mant'),
        ),
        migrations.AddConstraint(
            model_name='camion',
            constraint=models.CheckConstraint(check=models.Q(('capacidad_m3__gte', 0)), name='chk_camiones_capacidad_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='camion',
            constraint=models.CheckConstraint(check=models.Q(('kilometraje__gte', 0)), name='chk_camiones_km_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='camion',
            constraint=models.CheckConstraint(check=models.Q(('horas_operacion__gte', 0)), name='chk_camiones_horas_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='camion',
            constraint=models.CheckConstraint(check=models.Q(('consumo_l_100km__gte', 0)), name='chk_camiones_consumo_nonneg'),
        ),
    ]
