# Generated by Django 5.0.1 on 2025-12-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piedrinera', '0002_movimientoinventariopiedrinera'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregadopiedrinera',
            name='precio_descuento_m3',
            field=models.DecimalField(blank=True, db_column='precio_descuento_m3', decimal_places=2, help_text='Precio con descuento aplicado por m³ (opcional)', max_digits=12, null=True),
        ),
    ]
