# Generated by Django 5.0.1 on 2025-12-19 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piedrinera', '0003_add_precio_descuento'),
        ('planillas', '0006_alter_nominadetalle_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionPiedrinera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(db_column='codigo_lote', help_text='Código único del lote de producción', max_length=20, unique=True)),
                ('fecha_produccion', models.DateField(db_column='fecha_produccion', help_text='Fecha en que se realizó la producción')),
                ('hora_inicio_produccion', models.TimeField(db_column='hora_inicio_produccion', help_text='Hora de inicio de la producción')),
                ('hora_fin_produccion', models.TimeField(blank=True, db_column='hora_fin_produccion', help_text='Hora de finalización de la producción (opcional)', null=True)),
                ('volumen_planificado_m3', models.DecimalField(db_column='volumen_planificado_m3', decimal_places=2, default=0, help_text='Volumen planificado en metros cúbicos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('volumen_producido_m3', models.DecimalField(db_column='volumen_producido_m3', decimal_places=2, default=0, help_text='Volumen realmente producido en metros cúbicos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_total_q', models.DecimalField(db_column='costo_total_q', decimal_places=2, default=0, help_text='Costo total de la producción en quetzales', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_column='estado', default='EN_PROCESO', help_text='Estado actual del lote de producción', max_length=20)),
                ('calidad', models.CharField(blank=True, db_column='calidad', help_text='Calidad del lote producido', max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', help_text='Observaciones adicionales sobre la producción', null=True)),
                ('equipos_usados', models.JSONField(db_column='equipos_usados', default=list, help_text='Lista de IDs de equipos utilizados en la producción')),
                ('activo', models.BooleanField(db_column='activo', default=True, help_text='Indica si el registro está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('agregado', models.ForeignKey(db_column='agregado_id', help_text='Agregado que se está produciendo', on_delete=django.db.models.deletion.RESTRICT, related_name='producciones', to='piedrinera.agregadopiedrinera')),
                ('operador', models.ForeignKey(db_column='operador_id', help_text='Operador que realizó la producción', on_delete=django.db.models.deletion.RESTRICT, related_name='producciones_operadas', to='planillas.empleado')),
                ('supervisor', models.ForeignKey(db_column='supervisor_id', help_text='Supervisor responsable de la producción', on_delete=django.db.models.deletion.RESTRICT, related_name='producciones_supervisadas', to='planillas.empleado')),
            ],
            options={
                'verbose_name': 'Producción Piedrinera',
                'verbose_name_plural': 'Producciones Piedrinera',
                'db_table': 'produccion_piedrinera',
                'ordering': ['-fecha_produccion', '-hora_inicio_produccion'],
                'indexes': [models.Index(fields=['fecha_produccion'], name='idx_prod_piedrinera_fecha'), models.Index(fields=['estado'], name='idx_prod_piedrinera_estado'), models.Index(fields=['agregado'], name='idx_prod_piedrinera_agregado'), models.Index(fields=['supervisor'], name='idx_prod_piedrinera_supervisor'), models.Index(fields=['operador'], name='idx_prod_piedrinera_operador'), models.Index(fields=['equipos_usados'], name='idx_prod_piedrinera_equipos')],
            },
        ),
        migrations.AddConstraint(
            model_name='produccionpiedrinera',
            constraint=models.CheckConstraint(check=models.Q(('volumen_planificado_m3__gte', 0), ('volumen_producido_m3__gte', 0)), name='chk_volumen_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='produccionpiedrinera',
            constraint=models.CheckConstraint(check=models.Q(('costo_total_q__gte', 0)), name='chk_costo_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='produccionpiedrinera',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin_produccion__isnull', True), ('hora_fin_produccion__gt', models.F('hora_inicio_produccion')), _connector='OR'), name='chk_horas_validas'),
        ),
    ]
