# Generated by Django 5.0.1 on 2025-11-25 00:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferreteria', '0005_movimientoinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', help_text='Código único del material (ej: ACE-15W40-20L)', max_length=30, unique=True)),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre del material o repuesto', max_length=150)),
                ('marca', models.CharField(blank=True, db_column='marca', help_text='Marca del material (ej: Shell, Caterpillar)', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('stock_actual', models.DecimalField(db_column='stock_actual', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.DecimalField(db_column='stock_minimo', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_maximo', models.DecimalField(db_column='stock_maximo', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('STOCK_BAJO', 'Stock Bajo'), ('AGOTADO', 'Agotado')], db_column='estado', default='DISPONIBLE', max_length=20)),
                ('ubicacion', models.CharField(db_column='ubicacion', help_text='Ubicación del material en el almacén (ej: A-01-15)', max_length=50)),
                ('fecha_ultima_compra', models.DateField(blank=True, db_column='fecha_ultima_compra', null=True)),
                ('precio_unitario', models.DecimalField(db_column='precio_unitario', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumo_mensual_est', models.DecimalField(db_column='consumo_mensual_est', decimal_places=2, default=0, help_text='Consumo mensual estimado', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rotacion_est', models.DecimalField(db_column='rotacion_est', decimal_places=2, default=0, help_text='Rotación estimada', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_stock_est', models.IntegerField(db_column='dias_stock_est', default=0, help_text='Días de stock estimados', validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='materiales_taller', to='ferreteria.categoriaproducto')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', help_text='Proveedor principal del material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_taller', to='ferreteria.proveedor')),
                ('unidad_medida', models.ForeignKey(db_column='unidad_medida_id', on_delete=django.db.models.deletion.PROTECT, related_name='materiales_taller', to='ferreteria.unidadmedida')),
            ],
            options={
                'verbose_name': 'Material de Taller',
                'verbose_name_plural': 'Materiales de Taller',
                'db_table': 'materiales_taller',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='idx_mt_codigo'), models.Index(fields=['nombre', 'marca'], name='idx_mt_nombre_marca'), models.Index(fields=['estado'], name='idx_mt_estado'), models.Index(fields=['categoria'], name='idx_mt_categoria')],
            },
        ),
    ]
