# Generated by Django 5.0.1 on 2025-11-25 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigAutoField(db_column='id_servicio', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='codigo', help_text='Código único del servicio (ej: MANT-PREV-001)', max_length=50, unique=True)),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre del servicio', max_length=150)),
                ('descripcion', models.TextField(db_column='descripcion', help_text='Descripción detallada del servicio')),
                ('frecuencia', models.CharField(blank=True, db_column='frecuencia', help_text='Frecuencia recomendada (ej: Cada 250 horas)', max_length=50, null=True)),
                ('instrucciones_trabajo', models.TextField(blank=True, db_column='instrucciones_trabajo', help_text='Instrucciones paso a paso para realizar el servicio', null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', help_text='Observaciones adicionales', null=True)),
                ('duracion_horas', models.DecimalField(db_column='duracion_horas', decimal_places=2, help_text='Duración estimada en horas', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tecnicos_requeridos', models.IntegerField(db_column='tecnicos_requeridos', default=1, help_text='Número de técnicos requeridos', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_base', models.DecimalField(db_column='precio_base', decimal_places=2, help_text='Precio base del servicio en Quetzales', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='estado', default='ACTIVO', max_length=20)),
                ('creado_por', models.CharField(blank=True, db_column='creado_por', help_text='Usuario que creó el servicio', max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'taller_servicio',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.DecimalField(blank=True, db_column='cantidad_estimada', decimal_places=2, help_text='Cantidad típica de este material por servicio', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Material de Servicio',
                'verbose_name_plural': 'Materiales de Servicios',
                'db_table': 'taller_servicio_material',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id_tipo_equipo', models.BigAutoField(db_column='id_tipo_equipo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre del tipo de equipo (ej: Excavadoras, Camiones)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='estado', default='ACTIVO', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipo',
                'db_table': 'taller_tipo_equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id_categoria', models.BigAutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre de la categoría (ej: Mantenimiento, Reparación)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='estado', default='ACTIVO', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'db_table': 'taller_categoria_servicio',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_cat_serv_nombre'), models.Index(fields=['estado'], name='idx_cat_serv_estado')],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriaservicio',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['ACTIVO', 'INACTIVO'])), name='chk_cat_serv_estado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', help_text='Categoría del servicio', on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='taller.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='serviciomaterial',
            name='material',
            field=models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.RESTRICT, related_name='material_servicios', to='taller.materialtaller'),
        ),
        migrations.AddField(
            model_name='serviciomaterial',
            name='servicio',
            field=models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='servicio_materiales', to='taller.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='materiales',
            field=models.ManyToManyField(help_text='Materiales incluidos en este servicio', related_name='servicios', through='taller.ServicioMaterial', to='taller.materialtaller'),
        ),
        migrations.AddIndex(
            model_name='tipoequipo',
            index=models.Index(fields=['nombre'], name='idx_tipo_eq_nombre'),
        ),
        migrations.AddIndex(
            model_name='tipoequipo',
            index=models.Index(fields=['estado'], name='idx_tipo_eq_estado'),
        ),
        migrations.AddConstraint(
            model_name='tipoequipo',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['ACTIVO', 'INACTIVO'])), name='chk_tipo_eq_estado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_equipo',
            field=models.ForeignKey(db_column='id_tipo_equipo', help_text='Tipo de equipo al que aplica el servicio', on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='taller.tipoequipo'),
        ),
        migrations.AddIndex(
            model_name='serviciomaterial',
            index=models.Index(fields=['servicio'], name='idx_serv_mat_servicio'),
        ),
        migrations.AddIndex(
            model_name='serviciomaterial',
            index=models.Index(fields=['material'], name='idx_serv_mat_material'),
        ),
        migrations.AddConstraint(
            model_name='serviciomaterial',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_estimada__isnull', True), ('cantidad_estimada__gte', 0), _connector='OR'), name='chk_serv_mat_cantidad_nonneg'),
        ),
        migrations.AlterUniqueTogether(
            name='serviciomaterial',
            unique_together={('servicio', 'material')},
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['codigo'], name='idx_serv_codigo'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['nombre'], name='idx_serv_nombre'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['categoria'], name='idx_serv_categoria'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['tipo_equipo'], name='idx_serv_tipo_equipo'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['estado'], name='idx_serv_estado'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['ACTIVO', 'INACTIVO'])), name='chk_serv_estado'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(check=models.Q(('duracion_horas__gte', 0)), name='chk_serv_duracion_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(check=models.Q(('precio_base__gte', 0)), name='chk_serv_precio_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(check=models.Q(('tecnicos_requeridos__gte', 1)), name='chk_serv_tecnicos_min'),
        ),
    ]
