# Generated by Django 5.0.1 on 2025-11-28 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0003_remove_materiales_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='codigo', help_text='Código único de identificación de la maquinaria', max_length=50, unique=True)),
                ('nombre', models.CharField(db_column='nombre', help_text='Nombre o descripción de la maquinaria', max_length=200)),
                ('empresa', models.CharField(choices=[('F', 'E'), ('B', 'L'), ('P', 'I')], db_column='empresa', help_text='Empresa a la que pertenece la maquinaria', max_length=20, verbose_name='Empresa')),
                ('tipo_maquinaria', models.CharField(choices=[('EXCAVADORA', 'Excavadora'), ('RETROEXCAVADORA', 'Retroexcavadora'), ('CARGADOR', 'Cargador Frontal'), ('COMPACTADORA', 'Compactadora'), ('VIBRADOR', 'Vibrador de Concreto'), ('MEZCLADORA', 'Mezcladora de Concreto'), ('CORTADORA', 'Cortadora de Concreto'), ('GENERADOR', 'Generador'), ('COMPRESOR', 'Compresor de Aire'), ('SOLDADORA', 'Soldadora'), ('OTRO', 'Otro')], db_column='tipo_maquinaria', max_length=30, verbose_name='Tipo de Maquinaria')),
                ('marca', models.CharField(db_column='marca', max_length=100)),
                ('modelo', models.CharField(db_column='modelo', max_length=100)),
                ('numero_serie', models.CharField(blank=True, db_column='numero_serie', help_text='Número de serie del fabricante', max_length=100, null=True)),
                ('año_fabricacion', models.IntegerField(blank=True, db_column='año_fabricacion', help_text='Año de fabricación', null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('estado_actual', models.CharField(db_column='estado_actual', help_text='Estado actual: operativa, en mantenimiento, fuera de servicio, etc.', max_length=20)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, db_column='fecha_ultimo_mantenimiento', null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, db_column='fecha_proximo_mantenimiento', null=True)),
                ('horas_operacion', models.IntegerField(db_column='horas_operacion', default=0, help_text='Horas totales de operación', validators=[django.core.validators.MinValueValidator(0)])),
                ('kilometraje', models.IntegerField(db_column='kilometraje', default=0, help_text='Kilometraje (si aplica)', validators=[django.core.validators.MinValueValidator(0)])),
                ('seguro_vigente', models.BooleanField(db_column='seguro_vigente', default=True, help_text='Indica si el seguro está vigente')),
                ('documentacion_vigente', models.BooleanField(db_column='documentacion_vigente', default=True, help_text='Indica si la documentación está vigente')),
                ('ubicacion_actual', models.CharField(blank=True, db_column='ubicacion_actual', help_text='Ubicación actual de la maquinaria', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'db_table': 'maquinaria',
                'ordering': ['empresa', 'codigo'],
                'indexes': [models.Index(fields=['codigo'], name='idx_maquinaria_codigo'), models.Index(fields=['empresa'], name='idx_maquinaria_empresa'), models.Index(fields=['tipo_maquinaria'], name='idx_maquinaria_tipo'), models.Index(fields=['marca', 'modelo'], name='idx_maquinaria_marca_modelo'), models.Index(fields=['estado_actual'], name='idx_maquinaria_estado'), models.Index(fields=['fecha_proximo_mantenimiento'], name='idx_maquinaria_prox_mant'), models.Index(fields=['activo'], name='idx_maquinaria_activo')],
            },
        ),
        migrations.AddConstraint(
            model_name='maquinaria',
            constraint=models.CheckConstraint(check=models.Q(('horas_operacion__gte', 0)), name='chk_maquinaria_horas_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='maquinaria',
            constraint=models.CheckConstraint(check=models.Q(('kilometraje__gte', 0)), name='chk_maquinaria_km_nonneg'),
        ),
    ]
