# Generated by Django 5.0.1 on 2025-11-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='empresa',
            field=models.CharField(choices=[('FERRETERIA', 'Ferretería'), ('BLOQUERA', 'Bloquera'), ('PIEDRINERA', 'Piedrinera'), ('CONSTRUCTORA', 'Constructora')], db_column='empresa', help_text='Empresa a la que pertenece la maquinaria', max_length=20, verbose_name='Empresa'),
        ),
    ]
