# Generated by Django 5.0.1 on 2025-11-28 18:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0001_initial'),
        ('taller', '0005_alter_maquinaria_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(db_column='codigo_orden', help_text='Código único de la orden de trabajo', max_length=20, unique=True)),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('EMERGENCIA', 'Emergencia'), ('LEGAL_INSPECCION', 'Legal / Inspección')], db_column='tipo_mantenimiento', max_length=30, verbose_name='Tipo de Mantenimiento')),
                ('descripcion_trabajo', models.TextField(db_column='descripcion_trabajo', help_text='Descripción detallada del trabajo a realizar')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_column='prioridad', max_length=20, verbose_name='Prioridad')),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', help_text='Observaciones adicionales', null=True)),
                ('repuestos_externos', models.JSONField(blank=True, db_column='repuestos_externos', default=list, help_text='Lista de repuestos externos necesarios')),
                ('fecha_creacion_orden', models.DateField(db_column='fecha_creacion_orden', help_text='Fecha de creación de la orden')),
                ('fecha_inicio', models.DateField(db_column='fecha_inicio', help_text='Fecha de inicio del trabajo')),
                ('fecha_estimada_terminacion', models.DateField(db_column='fecha_estimada_terminacion', help_text='Fecha estimada de terminación')),
                ('fecha_terminacion_real', models.DateField(blank=True, db_column='fecha_terminacion_real', help_text='Fecha real de terminación', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], db_column='estado', default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('progreso', models.IntegerField(db_column='progreso', default=0, help_text='Porcentaje de progreso (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('costo_total_q', models.DecimalField(db_column='costo_total_q', decimal_places=2, default=0, help_text='Costo total en Quetzales', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por_id', help_text='Usuario que creó la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('maquinaria', models.ForeignKey(db_column='maquinaria_id', help_text='Maquinaria a la que aplica el mantenimiento', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='taller.maquinaria')),
                ('tecnico', models.ForeignKey(db_column='tecnico_id', help_text='Técnico asignado a la orden', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to='planillas.empleado')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'db_table': 'ordenes_trabajo',
                'ordering': ['-fecha_creacion_orden', '-created_at'],
                'indexes': [models.Index(fields=['codigo_orden'], name='idx_orden_codigo'), models.Index(fields=['maquinaria'], name='idx_orden_maquinaria'), models.Index(fields=['tecnico'], name='idx_orden_tecnico'), models.Index(fields=['estado'], name='idx_orden_estado'), models.Index(fields=['prioridad'], name='idx_orden_prioridad'), models.Index(fields=['tipo_mantenimiento'], name='idx_orden_tipo_mant'), models.Index(fields=['fecha_inicio'], name='idx_orden_fecha_inicio'), models.Index(fields=['fecha_estimada_terminacion'], name='idx_orden_fecha_est'), models.Index(fields=['activo'], name='idx_orden_activo')],
            },
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.CheckConstraint(check=models.Q(('progreso__gte', 0), ('progreso__lte', 100)), name='chk_orden_trabajo_progreso'),
        ),
    ]
