# Generated by Django 5.0.1 on 2026-01-04 21:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('Ferretería', 'Ferretería'), ('Bloquera', 'Bloquera'), ('Piedrinera', 'Piedrinera'), ('Taller', 'Taller')], db_column='empresa', max_length=30, verbose_name='Empresa')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], db_column='tipo', max_length=10, verbose_name='Tipo')),
                ('fecha_hora', models.DateTimeField(db_column='fecha_hora', default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('referencia', models.CharField(blank=True, db_column='referencia', help_text='FAC-001 / REC-001 / COMP-001 etc', max_length=50, null=True, verbose_name='Referencia')),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True, verbose_name='Descripción')),
                ('total', models.DecimalField(db_column='total', decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], db_column='estado', default='CONFIRMADO', max_length=12, verbose_name='Estado')),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='created_by_id', null=True, verbose_name='ID del Usuario que Creó')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'caja_movimiento',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='idx_caja_movimiento_fecha'), models.Index(fields=['tipo'], name='idx_caja_movimiento_tipo'), models.Index(fields=['empresa'], name='idx_caja_movimiento_empresa'), models.Index(fields=['referencia'], name='idx_caja_movimiento_referencia')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(db_column='producto_nombre', max_length=150, verbose_name='Nombre del Producto')),
                ('cantidad', models.DecimalField(db_column='cantidad', decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('costo_total', models.DecimalField(db_column='costo_total', decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('movimiento', models.ForeignKey(db_column='movimiento_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.movimientocaja', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento de Caja',
                'verbose_name_plural': 'Detalles de Movimiento de Caja',
                'db_table': 'caja_movimiento_detalle',
                'ordering': ['movimiento', 'id'],
                'indexes': [models.Index(fields=['movimiento'], name='idx_caja_detalle_movimiento')],
            },
        ),
    ]
