# Generated by Django 5.0.1 on 2026-01-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('ferreteria', '0006_add_precio_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocajadetalle',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, db_column='unidad_medida_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja_detalle', to='ferreteria.unidadmedida', verbose_name='Unidad de Medida'),
        ),
    ]
