# Generated by Django 5.0.1 on 2025-11-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0003_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Límite máximo de crédito permitido para el cliente', max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='permite_fiado',
            field=models.BooleanField(default=False, help_text='Indica si el cliente puede comprar a crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual de crédito utilizado por el cliente', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['permite_fiado'], name='clientes_permite_73b77a_idx'),
        ),
    ]
