# Generated by Django 5.0.1 on 2025-12-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0005_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_descuento',
            field=models.DecimalField(blank=True, db_column='precio_descuento', decimal_places=2, help_text='Precio con descuento aplicado (opcional)', max_digits=12, null=True),
        ),
    ]
